name: ETL Pipeline
on:
  schedule:
    - cron: '* * * * *'  
  workflow_dispatch:  

jobs:
  run-etl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python test.py
        
    - name: Run ETL pipeline
      run: |
        python load.py
        
    - name: Upload output CSV
      uses: actions/upload-artifact@v3.1.0
      with:
        name: etl-output
        path: output_*.csv
        if-no-files-found: error
        
    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: etl-logs
        path: etl_pipeline.log
